apiVersion: v1
kind: Pod
metadata:
  name: cms-portal
  labels:
    app: cms-portal
spec:
  containers:
    - name: cms-portal-container
      image: aluracursos/sistema-noticias:1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
