apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cms-statefulset
spec:
  selector:
    matchLabels:
      app: cms-portal
  serviceName: svc-cms-portal
  replicas: 1
  template:
    metadata:
      labels:
        app: cms-portal
    spec:
      containers:
        - name: cms-portal-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cms-portal-configmap
          volumeMounts:
            - name: images
              mountPath: /var/www/html/uploads
            - name: session
              mountPath: /tmp
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images-pvc
        - name: session
          persistentVolumeClaim:
            claimName: session-pvc
